"""empty message

Revision ID: 0470d8d56254
Revises: None
Create Date: 2016-10-02 10:39:04.058744

"""

# revision identifiers, used by Alembic.
revision = '0470d8d56254'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=8), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=True),
    sa.Column('date_of_turn', sa.DateTime(), nullable=True),
    sa.Column('fen_string', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    ### end Alembic commands ###
