"""empty message

Revision ID: 15ef47c2921f
Revises: fd065ce0dc17
Create Date: 2016-10-12 18:40:27.721230

"""

# revision identifiers, used by Alembic.
revision = '15ef47c2921f'
down_revision = 'fd065ce0dc17'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_username', sa.String(length=64), nullable=True))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['_username'])
    op.drop_column('users', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', '_username')
    ### end Alembic commands ###
