"""empty message

Revision ID: 87349fabfb0b
Revises: aaadb3e3933e
Create Date: 2016-10-04 23:13:23.600304

"""

# revision identifiers, used by Alembic.
revision = '87349fabfb0b'
down_revision = 'aaadb3e3933e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=8), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=True),
    sa.Column('date_of_turn', sa.DateTime(), nullable=True),
    sa.Column('fen_string', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('player_color', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('games')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('turn_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_of_turn', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fen_string', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='games_pkey')
    )
    op.drop_table('matches')
    op.drop_table('rounds')
    ### end Alembic commands ###
