"""empty message

Revision ID: 87d2247d9367
Revises: 87349fabfb0b
Create Date: 2016-10-04 23:29:30.073254

"""

# revision identifiers, used by Alembic.
revision = '87d2247d9367'
down_revision = '87349fabfb0b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('black_player', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('white_player', sa.Integer(), nullable=True))
    op.drop_constraint('matches_player_id_fkey', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'users', ['white_player'], ['id'])
    op.create_foreign_key(None, 'matches', 'users', ['black_player'], ['id'])
    op.drop_column('matches', 'player_color')
    op.drop_column('matches', 'player_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('player_color', sa.VARCHAR(length=24), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_player_id_fkey', 'matches', 'users', ['player_id'], ['id'])
    op.drop_column('matches', 'white_player')
    op.drop_column('matches', 'black_player')
    ### end Alembic commands ###
