"""empty message

Revision ID: 9bc711091150
Revises: 87d2247d9367
Create Date: 2016-10-05 23:15:09.638903

"""

# revision identifiers, used by Alembic.
revision = '9bc711091150'
down_revision = '87d2247d9367'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('black_player_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('match_url', sa.String(length=8), nullable=True))
    op.add_column('matches', sa.Column('white_player_id', sa.Integer(), nullable=True))
    op.drop_constraint('matches_black_player_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_white_player_fkey', 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'users', ['black_player_id'], ['id'])
    op.create_foreign_key(None, 'matches', 'users', ['white_player_id'], ['id'])
    op.drop_column('matches', 'white_player')
    op.drop_column('matches', 'black_player')
    op.drop_column('matches', 'match_id')
    op.add_column('rounds', sa.Column('match_url', sa.String(length=8), nullable=True))
    op.drop_column('rounds', 'match_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('match_id', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.drop_column('rounds', 'match_url')
    op.add_column('matches', sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('black_player', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('white_player', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key('matches_white_player_fkey', 'matches', 'users', ['white_player'], ['id'])
    op.create_foreign_key('matches_black_player_fkey', 'matches', 'users', ['black_player'], ['id'])
    op.drop_constraint(None, 'matches', type_='unique')
    op.drop_column('matches', 'white_player_id')
    op.drop_column('matches', 'match_url')
    op.drop_column('matches', 'black_player_id')
    ### end Alembic commands ###
