"""empty message

Revision ID: aaadb3e3933e
Revises: b32555d2a010
Create Date: 2016-10-03 23:17:21.537139

"""

# revision identifiers, used by Alembic.
revision = 'aaadb3e3933e'
down_revision = 'b32555d2a010'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_password')
    ### end Alembic commands ###
