"""empty message

Revision ID: b32555d2a010
Revises: None
Create Date: 2016-10-03 23:00:04.058410

"""

# revision identifiers, used by Alembic.
revision = 'b32555d2a010'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=8), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=True),
    sa.Column('date_of_turn', sa.DateTime(), nullable=True),
    sa.Column('fen_string', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('games')
    ### end Alembic commands ###
