"""empty message

Revision ID: c7d2c3d8c0f7
Revises: e444160bc0f9
Create Date: 2016-10-15 14:11:16.765084

"""

# revision identifiers, used by Alembic.
revision = 'c7d2c3d8c0f7'
down_revision = 'e444160bc0f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('black_notify', sa.Boolean(), nullable=True))
    op.add_column('matches', sa.Column('white_notify', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'white_notify')
    op.drop_column('matches', 'black_notify')
    ### end Alembic commands ###
