"""empty message

Revision ID: e017ed70b3f8
Revises: 15ef47c2921f
Create Date: 2016-10-14 19:58:01.470633

"""

# revision identifiers, used by Alembic.
revision = 'e017ed70b3f8'
down_revision = '15ef47c2921f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    op.drop_constraint('users__username_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', '_username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users__username_key', 'users', ['_username'])
    op.drop_column('users', 'username')
    ### end Alembic commands ###
