"""empty message

Revision ID: e444160bc0f9
Revises: 7086759e272f
Create Date: 2016-10-15 13:08:25.559321

"""

# revision identifiers, used by Alembic.
revision = 'e444160bc0f9'
down_revision = '7086759e272f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirmed')
    ### end Alembic commands ###
