"""empty message

Revision ID: e92bee2bb291
Revises: 9ebace1bda8c
Create Date: 2016-10-06 19:15:06.345739

"""

# revision identifiers, used by Alembic.
revision = 'e92bee2bb291'
down_revision = '9ebace1bda8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('match_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rounds', 'matches', ['match_id'], ['id'])
    op.drop_column('rounds', 'match_url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('match_url', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rounds', type_='foreignkey')
    op.drop_column('rounds', 'match_id')
    ### end Alembic commands ###
