"""empty message

Revision ID: fd065ce0dc17
Revises: 3e2eeaf53d87
Create Date: 2016-10-08 22:23:19.013282

"""

# revision identifiers, used by Alembic.
revision = 'fd065ce0dc17'
down_revision = '3e2eeaf53d87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_id', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_id')
    ### end Alembic commands ###
